apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: {{ .Values.service.port }}