pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "${env.AWS_REGION}"

        registry = "${env.FE_REGISTRY}"
        registryCredential = "${env.AWS_CREDENTIAL_ID}"
        version = "$BUILD_NUMBER"

        app_name = "frontend"
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh "pwd"
                    sh """
                        cd /var/lib/jenkins/workspace/frontend-ci-pipeline/src/frontend && pwd
                        docker build -t ${registry}:${app_name}:${version} .
                    """
                }
            }
        }
        stage('Build') {
            steps {
                sh 'echo Build...'
            }
        }
        stage('Deploy image') {
            steps {
                script{
                    docker.withRegistry("https://${registry}", "ecr:${AWS_DEFAULT_REGION}:${registryCredential}") {
                        sh "docker tag ${registry}:${app_name}:${version}"
                        sh "docker push ${registry}:${version}"
                    }
                }
            }
        }
    }
}
