pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = "${env.AWS_REGION}"
        registry = "${env.FE_REGISTRY}"
        registryCredential = "user-aws"
        app_name = "frontend"
    }

    parameters {
        string(name: 'version', defaultValue: 'latest', description: 'Application Version')
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                        echo 'Building Docker image...'
                        cd /var/lib/jenkins/workspace/frontend-ci-pipeline/src/frontend && pwd
                        docker build -t ${app_name}-${version} .
                    """
                }
            }
        }
        stage('Build') {
            steps {
                sh 'echo Build...'
            }
        }
        stage('Deploy image') {
            steps {
                script {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'user-aws', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                        sh "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${registry}"
                        sh "docker tag ${app_name}-${version} ${registry}:${version}"
                        sh "docker push ${registry}:${version}"
                    }
                }
            }
        }
    }
}
